name = "openmeter-customer-dashboard"
compatibility_date = "2024-01-01"

# This is an optional wrangler.toml for local development with Cloudflare Pages
# Not required for the frontend application, but useful for local testing

[build]
command = "npm run build"
cwd = "."

[pages]
directory = "dist"

# Optional: proxy API calls to local development server
[[pages.redirects]]
from = "/api/*"
to = "http://localhost:8888/api/:splat"
status = 200

# Serve SPA routes
[[pages.redirects]]
from = "/*"
to = "/index.html"
status = 200